name: Backup GitHub Repo to S3

on:
  push:
    branches:
      - main  # Trigger the backup on pushes to the main branch
  schedule:
    - cron: '*/5 * * * *'  # Runs the workflow every 5 minutes (UTC)

jobs:
  backup:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner

    steps:
    # Step 1: Checkout the repository content
    - name: Checkout repository content
      uses: actions/checkout@v3  # Checks out the repository code

    # Step 2: Set up AWS CLI credentials and configure AWS access
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    # Step 3: Create a zip of the repository
    - name: Zip the repository contents
      run: |
        zip -r backup-$(date +%Y-%m-%d-%H-%M-%S).zip . -x "*.git/*"

    # Step 4: Upload the zip file to S3
    - name: Upload to S3
      run: |
        aws s3 cp backup-$(date +%Y-%m-%d-%H-%M-%S).zip s3://${{ secrets.S3_BUCKET_NAME }}/backup.zip --region us-east-1

    # Step 5: Trigger SNS notification for the S3 event (automated via S3)
